### PR TITLE
Port to firefox

### PR DESCRIPTION
**Pull request by rnestler**
The options link in the pop-up does not work yet, but apart from that it is fine.

### CODE REVIEW

**Review by Janis-Leuenberger — CHANGES_REQUESTED** [review]
I know firefox does not support v3 yet but on the other hand chrome has deprecated v2: https://developer.chrome.com/docs/extensions/mv2/.

What is your plan to support both? and what about CD?

**Comment by rnestler** [comment]
> I know firefox does not support v3 yet but on the other hand chrome has deprecated v2: https://developer.chrome.com/docs/extensions/mv2/.

Argh, didn't realize the hard deprecated it already. In the browser it shows that support will be removed in 2023... Well that puts cross browser extension developers in an awkward situation :confused:

**Comment by Janis-Leuenberger** [comment]
An easy solution would to be create a separate master branch for firefox which you can compile yourself and (if you want) upload to the store.

I think the proper solution is to either have two subrepos with shared folders or override the necessary files during some compilation step. Then you can connect to their api (if they have one) and upload it using CD. This would be quite a bit of work IMO and I would not enjoy doing it :)

**Review by Janis-Leuenberger — APPROVED** [review]
It would be cool if the integration tests ran in firefox. Don't know if it's possible but if you want you can try.

Can you update the Readme to include the state of the firefox extension?

Thanks for porting btw :)

**Comment by rnestler** [comment]
> Can you update the Readme to include the state of the firefox extension?

On the master branch or master-firefox? Or both?

**Comment by Janis-Leuenberger** [comment]
I'd say on the master branch you add `For firefox go to this branch` and on the firefox branch add unique useful stuff about the branch. But feel free to do whatever you think is best.

**Pull request merged**
